# Generated by Django 5.1.1 on 2024-09-26 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookmarkedRestaurants',
            new_name='BookmarkedRestaurant',
        ),
        migrations.AlterField(
            model_name='restaurantphoto',
            name='image',
            field=models.ImageField(upload_to='restaurant_photos/'),
        ),
    ]
